//
//  UIColor+Untitled.swift
//
//  Generated by Zeplin on 10/29/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

import UIKit

extension UIColor {
    
    class func isWhiteColor() -> UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 1.0)

    }
    
    class func isGreyColor() -> UIColor {
        return UIColor(red: 147.0 / 255.0, green: 164.0 / 255.0, blue: 171.0 / 255.0, alpha: 1.0)
    }

    class func isAppleGreenColor() -> UIColor {
        return UIColor(red: 126.0 / 255.0, green: 211.0 / 255.0, blue: 33.0 / 255.0, alpha: 1.0)
    }

    class func uisWarmGreyColor() -> UIColor {
        return UIColor(white: 155.0 / 255.0, alpha: 1.0)
    }

    class func isLeafyGreenColor() -> UIColor {
        return UIColor(red: 66.0 / 255.0, green: 188.0 / 255.0, blue: 65.0 / 255.0, alpha: 1.0)
    }

    class func isTealColor() -> UIColor {
        return UIColor(red: 0.0, green: 150.0 / 255.0, blue: 136.0 / 255.0, alpha: 1.0)
    }

    class func isFrenchBlueColor() -> UIColor {
        return UIColor(red: 64.0 / 255.0, green: 82.0 / 255.0, blue: 182.0 / 255.0, alpha: 1.0)
    }

    class func isCornFlowerBlueColor() -> UIColor {
        return UIColor(red: 84.0 / 255.0, green: 118.0 / 255.0, blue: 253.0 / 255.0, alpha: 1.0)
    }

    class func isIrisColor() -> UIColor {
        return UIColor(red: 126.0 / 255.0, green: 86.0 / 255.0, blue: 196.0 / 255.0, alpha: 1.0)
    }

    class func isFlatGreenColor() -> UIColor {
        return UIColor(red: 140.0 / 255.0, green: 194.0 / 255.0, blue: 74.0 / 255.0, alpha: 1.0)
    }

    class func isSicklyGreenColor() -> UIColor {
        return UIColor(red: 206.0 / 255.0, green: 216.0 / 255.0, blue: 65.0 / 255.0, alpha: 1.0)
    }

    class func isAzureColor() -> UIColor {
        return UIColor(red: 4.0 / 255.0, green: 169.0 / 255.0, blue: 245.0 / 255.0, alpha: 1.0)
    }

    class func isTurquoiseBlueColor() -> UIColor {
        return UIColor(red: 0.0, green: 188.0 / 255.0, blue: 213.0 / 255.0, alpha: 1.0)
    }

    class func isBlueyPurpleColor() -> UIColor {
        return UIColor(red: 104.0 / 255.0, green: 58.0 / 255.0, blue: 184.0 / 255.0, alpha: 1.0)
    }

    class func isSunshineYellowColor() -> UIColor {
        return UIColor(red: 255.0 / 255.0, green: 235.0 / 255.0, blue: 60.0 / 255.0, alpha: 1.0)
    }

    class func isTangerineColor() -> UIColor {
        return UIColor(red: 255.0 / 255.0, green: 151.0 / 255.0, blue: 2.0 / 255.0, alpha: 1.0)
    }

    class func isTomatoColor() -> UIColor {
        return UIColor(red: 231.0 / 255.0, green: 78.0 / 255.0, blue: 64.0 / 255.0, alpha: 1.0)
    }

    class func isWarmGreyColor() -> UIColor {
        return UIColor(white: 158.0 / 255.0, alpha: 1.0)
    }

    class func isBasicBrownColor() -> UIColor {
        return UIColor(red: 121.0 / 255.0, green: 85.0 / 255.0, blue: 73.0 / 255.0, alpha: 1.0)
    }

    class func isBlueGreyColor() -> UIColor {
        return UIColor(red: 96.0 / 255.0, green: 125.0 / 255.0, blue: 141.0 / 255.0, alpha: 1.0)
    }

    class func isOrangeRedColor() -> UIColor {
        return UIColor(red: 254.0 / 255.0, green: 87.0 / 255.0, blue: 32.0 / 255.0, alpha: 1.0)
    }

    class func isOrangeyYellowColor() -> UIColor {
        return UIColor(red: 251.0 / 255.0, green: 193.0 / 255.0, blue: 31.0 / 255.0, alpha: 1.0)
    }

    class func isRustyRedColor() -> UIColor {
        return UIColor(red: 209.0 / 255.0, green: 29.0 / 255.0, blue: 22.0 / 255.0, alpha: 1.0)
    }

    class func isGreyishBrownColor() -> UIColor {
        return UIColor(red: 77.0 / 255.0, green: 52.0 / 255.0, blue: 46.0 / 255.0, alpha: 1.0)
    }
    class func isOptimisticOrangeColor() -> UIColor {
        return UIColor(red: 245.0 / 255.0, green: 130 / 255, blue: 15 / 255, alpha: 1.0)
    }
}
